config/routes.rb
Rails.application.routes.draw do
  resources :notes
  root "home#home"
  get 'contact',to: 'home#contact'
  post 'request_contact',to: 'home#request_contact'

end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :title, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def contact

  end

  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]
    if email.blank?
    flash[:alert] = I18n.t('home.request_contact.no_email')
    else
    # Send an email
    flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
    redirect_to root_path
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/contact.html.haml
%h1= t('.title')
%p= t('.contact_us')


= form_tag request_contact_path, method: 'post' do

  = label_tag :name, t('.name')
  = text_field_tag :name, '', title: t('.enter_name'), size: 50

  = label_tag :email, t('.email')
  = email_field_tag :email, '', title: t('.enter_email')

  = label_tag :telephone, t('.telephone')
  = telephone_field_tag :telephone, '', title: t('.enter_telephone')

  = label_tag :message, t('.message')
  = text_field_tag :message, '', title: t('.enter_message'), size: 100

  = submit_tag t('.submit')

app/views/home/home.html.haml
%html
  %head
    %title Depot
%body

  %h1= t('.title')
  %p= t('.welcome')
  =link_to('Contact us',"/contact")
  =link_to('View Database',"/notes")

app/views/layouts/application.html.haml
!!!

%html
  %head
    %meta{'charset' => 'utf-8'}
    %meta{'http-equiv' => 'x-ua-compatible', 'content' => 'ie=edge'}

    %title= t('app_title')

    %meta{'name' => 'description', 'content' => t('app_description')}
    %meta{'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1'}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'modernizr'
    = csrf_meta_tags

  %body
    - flash.each do |key, value|
      = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?

    = render 'shared/header'

    = yield
    = render 'shared/footer'

app/views/notes/_form.html.haml
= form_for @note do |f|
  - if @note.errors.any?
    #error_explanation
      %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      %ul
        - @note.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/notes/edit.html.haml
%h1 Editing note

= render 'form'

= link_to 'Show', @note
\|
= link_to 'Back', notes_path

app/views/notes/index.html.haml
%h1 Listing notes

%table
  %thead
    %tr
      %th Title
      %th Description
      %th
      %th
      %th

  %tbody
    - @notes.each do |note|
      %tr
        %td= note.title
        %td= note.description
        %td= link_to 'Show', note
        %td= link_to 'Edit', edit_note_path(note)
        %td= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Note', new_note_path

app/views/notes/new.html.haml
%h1 New note

= render 'form'

= link_to 'Back', notes_path

app/views/notes/show.html.haml
%p
  %b Title:
  = @note.title
%p
  %b Description:
  = @note.description

= link_to 'Edit', edit_note_path(@note)
\|
= link_to 'Back', notes_path

app/views/shared/_footer.html.haml
%footer
  %p= 'lol'

app/views/shared/_header.html.haml
%header
  %h1 header1